name: analog_clock
description: Analog clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/backgrounds/0/
    - assets/images/backgrounds/1/
    - assets/images/backgrounds/2/
    - assets/images/backgrounds/3/
    - assets/images/backgrounds/4/
    - assets/images/backgrounds/5/
    - assets/images/ring.png
    - assets/images/weathericons/day_cloudy.png 
    - assets/images/weathericons/night_cloudy.png
    - assets/images/weathericons/foggy.png
    - assets/images/weathericons/day_rainy.png
    - assets/images/weathericons/night_rainy.png
    - assets/images/weathericons/day_snowy.png
    - assets/images/weathericons/night_snowy.png
    - assets/images/weathericons/sunny.png
    - assets/images/weathericons/night_clear.png
    - assets/images/weathericons/day_thunderstorm.png
    - assets/images/weathericons/night_thunderstorm.png
    - assets/images/weathericons/windy.png
  
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa/Comfortaa-Regular.ttf
